version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignored_updates:
    - match:
        # react-scripts has a 6.x dependency, want to avoid updating this until then
        dependency_name: 'eslint'
    - match:
        # need to update this manually to resolve any issues
        dependency_name: '@typescript-eslint/eslint-plugin'
    - match:
        # need to update this manually to resolve any issues
        dependency_name: '@typescript-eslint/parser'
